{{- if .Values.configServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loyalty-platform-v1.fullname" . }}-config-server
  labels:
    app.kubernetes.io/component: config-server
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    {{- include "loyalty-platform-v1.labels" . | nindent 4 }}
  {{- with .Values.configServer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.configServer.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: config-server
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Release.Name }}
  strategy:
    {{- toYaml .Values.configServer.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: config-server
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
      {{- with .Values.configServer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.configServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: config-server
          image: "{{ .Values.configServer.image.repository }}:{{ .Values.configServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.configServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.configServer.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "loyalty-platform-v1.fullname" . }}-config-server-env
            - secretRef:
                name: {{ include "loyalty-platform-v1.fullname" . }}-config-server-secret
          {{- if .Values.configServer.env }}
          env:
            {{- toYaml .Values.configServer.env | nindent 12 }}
          {{- end }}
          {{- if .Values.configServer.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.configServer.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.configServer.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.configServer.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.configServer.resources }}
          resources:
            {{- toYaml .Values.configServer.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.configServer.persistence.enabled }}
          volumeMounts:
            - name: config-server-data
              mountPath: {{ .Values.configServer.persistence.mountPath }}
              {{- if .Values.configServer.persistence.subPath }}
              subPath: {{ .Values.configServer.persistence.subPath }}
              {{- end }}
          {{- end }}
      {{- with .Values.configServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.configServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.configServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.configServer.persistence.enabled }}
      volumes:
        - name: config-server-data
          persistentVolumeClaim:
            claimName: {{ include "loyalty-platform-v1.fullname" . }}-config-server-data
      {{- end }}
{{- end }}
