{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loyalty-platform-v1.fullname" . }}-nginx
  labels:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    {{- include "loyalty-platform-v1.labels" . | nindent 4 }}
  {{- with .Values.nginx.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.nginx.service.type "NodePort") .Values.nginx.service.nodePort }}
      nodePort: {{ .Values.nginx.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/component: nginx
    {{- include "loyalty-platform-v1.selectorLabels" . | nindent 4 }}
{{- end }}
