{{- if .Values.postgresql.proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loyalty-platform-v1.fullname" . }}-postgresql-proxy
  labels:
    app.kubernetes.io/component: postgresql-proxy
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    {{- include "loyalty-platform-v1.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: postgresql-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgresql-proxy
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: postgresql-proxy
          image: "{{ .Values.postgresql.proxy.image.repository }}:{{ .Values.postgresql.proxy.image.tag }}"
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRES_HOST
              value: "{{ include "loyalty-platform-v1.postgresql.fullname" . }}"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.auth.username }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "loyalty-platform-v1.fullname" . }}-postgresql
                  key: postgres-password
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loyalty-platform-v1.fullname" . }}-postgresql-proxy
  labels:
    app.kubernetes.io/component: postgresql-proxy
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    {{- include "loyalty-platform-v1.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/component: postgresql-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
