{{- if .Values.postgresql.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loyalty-platform-v1.fullname" . }}-postgresql-nodeport
  labels:
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    {{- include "loyalty-platform-v1.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: {{ .Values.postgresql.nodePort.port | default 30432 }}
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
